INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("PC");
INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("furniture");
INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("common");
INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("router");
INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("printer");
INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("monitor");
INSERT INTO OFFICE_OBJECT_TYPE(name) VALUES("laptop");

