  INSERT INTO office_object(name, office_object_type_id) VALUES("Gygabit 2345",1);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Marvelous PC",1);
  INSERT INTO office_object(name, office_object_type_id) VALUES("TransDevil 003",1);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Samsung laptop 0928",7);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Катюшин ноут",7);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Серегин ноут",7);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Компьютер начальника",7);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Lenovo Sf235",7);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Dell Rg233",6);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Samsung 234",6);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Dlink dir-300",4);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Asus RT02",4);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Стол семена",2);
  INSERT INTO office_object(name, office_object_type_id) VALUES("Стол начальника",2);
